language: python
python:
    - '3.6'
env:
    - DJANGO_SECRET_KEY="04p_d^@)^bucp&sns1#l+#9x3nf*!6bqwajh(zgnxae_s2bhp=", TRAVIS="True"
before_install:
    - pipenv install
install: pipenv run pip install --upgrade 'sentry-sdk==0.16.1'
script: pipenv run python manage.py test
